config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "care_helper#index"

  resources :profiles, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
  
end

app/models/contact.rb
class Contact < ApplicationRecord

  belongs_to :profile

end

app/models/gender.rb
class Gender < ActiveHash::Base
  
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '男性' },
    { id: 2, name: '女性' },
    { id: 3, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :articles

end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user
  has_many :contacts

  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender

end

app/models/profile_contact.rb
class ProfileContact
  include ActiveModel::Model
  attr_accessor :patient, :birth_date, :gender_id, :blood_type, :family, :history, :disease, :medications, :user_id,
                :person, :relationship, :address, :email, :phone, :image

  validate :validate_image

  with_options presence: true do
    validates :patient
    validates :birth_date
    validates :gender_id, numericality: { other_than: 0, message: "を選択してください"}
    validates :blood_type
    validates :family

    validates :person
    validates :relationship
    validates :address
    validates :email
    validates :phone, length: {minimum: 10, message: "は10桁以上を入力してください"}, format: {with: /\A[0-9]{10,11}\z/, message: "は半角数値を入力してください"}

    validates :history
    validates :disease
    validates :medications
  end

  def save
    profile = Profile.create(
      patient: patient, birth_date: birth_date, gender_id: gender_id, blood_type: blood_type, family: family, history: history, disease: disease, medications:medications
    )
    Contact.create(
      person: person, relationship: relationship, address: address, email: email, phone: phone
    )
  end

  private

  def validate_image
    if image.blank?
      errors.add(:image, "のファイルを選択してください")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :profiles

  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end
end

app/controllers/care_helper_controller.rb
class CareHelperController < ApplicationController
  
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
    @profile_contact = ProfileContact.new
  end

  def create
    @profile_contact = ProfileContact.new(profile_params)
    if @profile_contact.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def profile_params
    params.require(:profile_contact).permit(
      :patient, :birth_date, :gender_id, :blood_type, :family, :history, :disease, :medications, :image,
      :person, :relationship, :address, :email, :phone
    ).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/care_helper/_care_record.html.erb
<%# 記録一覧 %>
<div class="records">

  <div class="record">
    <div class="record-p-upper">
      <div class="record-date">
        20xx/xx/xx(木) xx:xx
      </div>
    </div>

    <div class="record-p-lower">
      <div class="record-text">
        記録内容
      </div>
      <div class="record-user">
        職員名
      </div>
    </div>
  </div>

  <div class="record">

    <div class="record-p-upper">
      <div class="record-date">
        20xx/xx/xx(金) xx:xx
      </div>
    </div>

    <div class="record-p-lower">
      <div class="record-text">
        記録内容
      </div>
      <div class="record-user">
        職員名
      </div>
    </div>

  </div>

</div>
<%# 記録フォーム %>
<div class="record-form">

  <div class="form-input">
    <input class="form-text" placeholder= "記録内容を入力">
  </div>

  <div class = "category-options">
      <label><input type="checkbox" name="category" value="adl">
        <a>ＡＤＬ</a>
      </label>
        <label><input type="checkbox" name="category" value="bpsd">
        <a>ＢＰＳＤ</a>
      </label>
      <label><input type="checkbox" name="category" value="qol">
        <a>ＱＯＬ</a>
      </label>
      <label><input type="checkbox" name="category" value="community">
        <a>社交</a>
      </label>
      <label><input type="checkbox" name="category" value="trouble">
        <a>トラブル</a>
      </label>
      <label><input type="checkbox" name="category" value="medical">
        <a>医療</a>
      </label>
      <label><input type="checkbox" name="category" value="rehabilitation">
        <a>リハビリ</a>
      </label>
      <label><input type="checkbox" name="category" value="other">
        <a>その他</a>
      </label>
    </div>
    
  <input class="form-submit" type="submit" value="保存">

</div>

app/views/care_helper/_header_menu.html.erb
<div class="account">

  <%= current_user.name %>

  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>

  </div>

  <div class = "create-patient-profile">
    <%= link_to '利用者登録', new_profile_path %>
  </div>
  <div class = "search">
    <div class="form-input">
      <input class="form-text" placeholder= "検索ワードを入力">
    </div>
  </div>
  <div class = "vault">
    <a href = "#">記録保管庫</a>
  </div>

app/views/care_helper/_patient_list.html.erb
<div class="patients">

  <div class="patient-name">
    <a href="#">利用者Ａ</a>
  </div>
  <div class="patient-name">
    <a href="#">利用者Ｂ</a>
  </div>
  
</div>

app/views/care_helper/_patient_profile.html.erb
<div class="profile">

  <div class="profile-p-upper">
    <div class="base-profile">
      <div class="title">基本情報</div>
      氏名、生年月日、現在の年齢、性別、血液型、家族などの基本情報を表示。
    </div>
    <div class="patient-image">
      顔写真
    </div>
  </div>
  <div class="profile-p-lower">
    <div class="contact-list">
      <div class="title">連絡先１</div>
      <div class="contact">
        <div class="person-data">
          <div class="person">≪氏名≫</div>
          <div class="relationship">≪関係≫</div>
          <div class="address">≪住所≫</div>
        </div>
        <div class="person-tel">
          <div class="email">email:xxxx@xxx.xxx</div>
          <div class="phone">phone:000-0000-0000</div>
        </div>
      </div>
      <div class="title">連絡先２</div>
      <div class="contact">
        <div class="person-data">
          <div class="person">≪氏名≫</div>
          <div class="relationship">≪関係≫</div>
          <div class="address">≪住所≫</div>
        </div>
        <div class="person-tel">
          <div class="email">email:xxxx@xxx.xxx</div>
          <div class="phone">phone:000-0000-0000</div>
        </div>
      </div>

    </div>
    <div class="history">
      <div class="title">既往歴</div>
        出身地、転居歴、職歴、性格、家族関係などを表示。
    </div>
    <div class="disease">
      <div class="title">疾患</div>
        認知症や精神疾患、持病や怪我など現在の疾患を表示。
    </div>
    <div class="medications">
      <div class="title">服用薬</div>
        現在服用されている薬の種類を表示。
    </div>
    <div class="topic">
      <div class="title">
      <div class = "category-options">
      <label><input type="checkbox" name="category" value="adl">
        <a>ＡＤＬ</a>
      </label>
        <label><input type="checkbox" name="category" value="bpsd">
        <a>ＢＰＳＤ</a>
      </label>
      <label><input type="checkbox" name="category" value="qol">
        <a>ＱＯＬ</a>
      </label>
      <label><input type="checkbox" name="category" value="community">
        <a>社交</a>
      </label>
      <label><input type="checkbox" name="category" value="trouble">
        <a>トラブル</a>
      </label>
      <label><input type="checkbox" name="category" value="medical">
        <a>医療</a>
      </label>
      <label><input type="checkbox" name="category" value="rehabilitation">
        <a>リハビリ</a>
      </label>
      <label><input type="checkbox" name="category" value="other">
        <a>その他</a>
      </label>
    </div>
      </div>
      選択されたタグを含む、最新の記録５件を表示。
    </div>
  </div>

</div>

app/views/care_helper/index.html.erb
<div class="header-menu">
  <%= render "header_menu" %>
</div>

<div class="body">

  <div class="patient-list">
    <%= render "patient_list" %>
  </div>

  <div class="care-record">
    <%= render "care_record" %>
  </div>

  <div class="patient-profile">
    <%= render "patient_profile" %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CareHelper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/profiles/new.html.erb
<div class='patient-profile-form'>
  <%=form_with model: @profile_contact, url: profiles_path, local: true do |f|%>
    <div class='patient-profile-form__field'>
      <h2>利用者情報の登録</h2>

      <%= render 'error_messages', model: @profile_contact %>

      <div class="img-upload">
        <div class="weight-bold-text">
          <div class='patient-profile-form-text'>顔写真</div>
        </div>
        <div class="click-upload">
          <p> クリックしてファイルをアップロード</p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <div class='form-group'>
        <div class='patient-profile-form-text'>氏名</div>
        <%= f.text_field :patient, class: 'input-default', id:"patient", placeholder: '例）猫田花子'%>
      </div>
      <div class='form-group'>
        <div class='patient-profile-form-text'>生年月日</div>
        <div class='side-by-side'>
          <%#= raw sprintf(
            f.date_select(
            :birth_date,
            use_month_numbers: true,
            prompt: '--',
            start_year: 1930,
            end_year: (Time.now.year - 20),
            date_separator: '%s'),
            "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>"
          %>
          <%= f.date_field(
            :birth_date,
            use_month_numbers: true,
          )%>
        </div>
      </div>
    </div>
    <div class='form-group'>
        <div class='patient-profile-form-text'>性別</div>
        <%= f.collection_select(
          :gender_id, Gender.all,
          :id,
          :name,
          {},
          {class:"select-box", id:"gender"}) %>
    </div>
    <div class='form-group'>
        <div class='patient-profile-form-text'>血液型</div>
        <%= f.text_field :blood_type, class: 'input-default', id:"blood-type", placeholder: '例）B'%>
    </div>
    <div class='form-group'>
        <div class='patient-profile-form-text'>家族</div>
        <%= f.text_field :family, class: 'input-default', id:"family", placeholder: '例）夫、長男、長女、次男、孫（女）'%>
    </div>
    <%# 連絡先 %>
    <div class='form-group'>
      <div class='patient-profile-form-text'>連絡先</div>
      <div class='side-by-side'>
        <div class='form-group'>
          氏名
          <%= f.text_field :person, class: 'input-default', id:"person", placeholder: '例）猫田太郎'%>
        </div>
        <div class='form-group'>
          関係
          <%= f.text_field :relationship, class: 'input-default', id:"relationship", placeholder: '例）長男'%>
        </div>
        <div class='form-group'>
          住所
          <%= f.text_field :address, class: 'input-default', id:"address", placeholder: '例）〇〇県〇〇市〇〇xx-xx'%>
        </div>
      </div>
      <div class='side-by-side'>
        <div class='form-group'>
          Ｅメール
          <%= f.text_field :email, class: 'input-default', id:"email", placeholder: '例）nekoneko@test.com', pattern: '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', title: '有効なメールアドレスを入力してください'%>
        </div>
        <div class='form-group'>
          電話番号
          <%= f.text_field :phone, class: 'input-default', id:"phone", placeholder: '例）08012345678', pattern: '[0-9]+'%>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class='patient-profile-form-text'>既往歴</div>
      <%= f.text_area :history, class:"patient-text", id:"history", placeholder:"1,000文字まで）出身地、転居歴、職歴、性格、家族関係など）例）〇〇県〇〇市〇〇に生まれる。〇才で結婚し〇〇へ転居。〇才からスーパーで働き始める。大らかな性格。" ,rows:"7" ,maxlength:"1000" %>
    </div>
    <div class="form-group">
      <div class='patient-profile-form-text'>疾患</div>
      <%= f.text_area :disease, class:"patient-text", id:"disease", placeholder:"1,000文字まで）要支援度、要介護度、認知症の種類、糖尿病などの持病、身体麻痺、禁忌事項など",rows:"7" ,maxlength:"1000" %>
    </div>
    <div class="form-group">
      <div class='patient-profile-form-text'>服用薬</div>
      <%= f.text_area :medications, class:"patient-text", id:"medications", placeholder:"1,000文字まで）薬の名前、服用頻度、薬の効能、禁忌事項など",rows:"7" ,maxlength:"1000" %>
    </div>

    <div class='patient-profile-form__field'>
        <%= f.submit class: 'cpatient-profile-form__action-btn'%>
    </div>
  <% end %>
</div>